### ISSUE TITLE
Not working add datasource in grafana cloud

### ISSUE THREAD

**Issue by sdg9670f** [grafana/grafana-amazonprometheus-datasource#200]
I got this error when I tried to type connection url
so, couldn't edit aws prometheus datasource.

```
An unexpected error happened
Details
TypeError: Cannot assign to read only property 'sigV4Auth' of object '[object Object]'

    at ZT (https://someworkspace.grafana.net/public/plugins/grafana-amazonprometheus-datasource/module.js?_cache=1.0.0:2:681022)
    at https://someworkspace.grafana.net/public/plugins/grafana-amazonprometheus-datasource/module.js?_cache=1.0.0:2:683505
    at div
    at Ss (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/Connections.f0d3fc3c0875f139e040.js:48:2378)
    at r (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:1:183)
    at form
    at Es (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/Connections.f0d3fc3c0875f139e040.js:48:5847)
    at Is (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/Connections.f0d3fc3c0875f139e040.js:48:5404)
    at p (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:231:17991)
    at div
    at div
    at div
    at d (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:231:17322)
    at div
    at K (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:231:21920)
    at $s (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/Connections.f0d3fc3c0875f139e040.js:48:8783)
    at Os (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/Connections.f0d3fc3c0875f139e040.js:48:9179)
    at V (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1018:29174)
    at V (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1018:31352)
    at Js (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/Connections.f0d3fc3c0875f139e040.js:56:2221)
    at Suspense
    at g (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:63:133851)
    at Tr (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:187:12305)
    at V (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1018:29174)
    at lo (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1009:4452)
    at as (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1009:12001)
    at Ut (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1018:17388)
    at V (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1018:31352)
    at div
    at https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:82:52949
    at main
    at div
    at div
    at div
    at Cs (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:187:2406)
    at div
    at bi (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:187:7580)
    at lo (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1009:4452)
    at as (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1009:12001)
    at fs (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1009:11337)
    at yr (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1018:17687)
    at V (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1018:25388)
    at v (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:164:8978)
    at b (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1371:112899)
    at c (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:432:27874)
    at g (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:63:133851)
    at o (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:63:134360)
    at wt (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/9006.b4cc3b7e5a15e74b7f70.js:1375:508)
    at qi (https://grafana-assets.grafana.net/grafana/11.2.0-73830/public/build/6311.e2995c9b9e3ad85768d7.js:187:14420)
```

**Comment by njvrzm** [comment]
Thank you for the report! This is fixed now with version 1.0.1 of the plugin. Let us know if you run into any more issues.
